# @generated by tools/generate_contracts.py from contracts/schemas/ — DO NOT EDIT (repo-arch §13).

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from .. import common_schema
from . import manufacturing_request_schema


class EngineeringVerificationStatus(StrEnum):
    """
    Closed enum (frozen, spec §5.8). Consistent with source.kind.
    """

    velith_verified = "velith_verified"
    engineer_declared = "engineer_declared"


class DesignSourceKind(StrEnum):
    manufacturing_request = "manufacturing_request"
    velith_engineering_result = "velith_engineering_result"


@dataclass
class DesignSource:
    kind: DesignSourceKind
    ref: common_schema.Ref


@dataclass
class DesignArtifactRef:
    """
    OPAQUE reference (e.g. STEP or Velith artifact). Never parsed by RM1.
    """

    media_type: str
    id: common_schema.Uuid
    content_hash: common_schema.ContentHash


@dataclass
class DesignInput:
    """
    Normalized opaque design carried into planning; one contract for both intake paths (RM1 spec §7; package §3.2). schema_version 1.0.0. Identity view excludes design_input_id and provenance.
    """

    schema_version: common_schema.SemVer
    design_input_id: common_schema.Uuid
    engineering_verification_status: EngineeringVerificationStatus
    source: DesignSource
    material: str
    stock_form: manufacturing_request_schema.StockForm
    declared_operations: list[manufacturing_request_schema.DeclaredOperation]
    quantity: int
    provenance: common_schema.Provenance
    material_code: str | None = None
    tolerances: manufacturing_request_schema.Tolerances | None = None
    design_artifact_ref: DesignArtifactRef | None = None
