# @generated by tools/generate_contracts.py from contracts/schemas/ — DO NOT EDIT (repo-arch §13).

from __future__ import annotations

from dataclasses import dataclass

from .. import common_schema


@dataclass
class ProductIntent:
    summary: str


@dataclass
class ManufacturingTask:
    """
    A manufacturing task bound to one DesignInput (package §3.3). schema_version 1.0.0. Identity view excludes task_id.
    """

    schema_version: common_schema.SemVer
    task_id: common_schema.Uuid
    product_intent: ProductIntent
    design_input_ref: common_schema.Ref
