# @generated by tools/generate_contracts.py from contracts/schemas/ — DO NOT EDIT (repo-arch §13).

from __future__ import annotations

from dataclasses import dataclass

from .. import common_schema
from ..consumed.noetica import verdict_schema
from . import design_input_schema, manufacturing_task_schema, production_plan_schema


@dataclass
class Timing:
    """
    EXCLUDED from content_hash.
    """

    created_at: common_schema.Rfc3339
    plan_ms: float
    verify_ms: float


@dataclass
class ManufacturingEpisode:
    """
    Experience-Flow DATA contract (Law 21; package §3.6). MP produces the content; Noetica owns the lifecycle framework (deferred). Serialized as append-only JSONL (one canonical-JSON object per line). episode_id is deterministic = uuid5(NS_MP, content_hash). Persisted episodes NEVER carry status INFRA_ERROR. Identity view excludes episode_id, content_hash (self), and timing.
    """

    schema_version: common_schema.SemVer
    episode_id: common_schema.Uuid
    task: manufacturing_task_schema.ManufacturingTask
    design_ref: common_schema.Ref
    engineering_verification_status: design_input_schema.EngineeringVerificationStatus
    plan: production_plan_schema.ProductionPlan
    verdict: verdict_schema.Verdict
    capability_model_version: common_schema.SemVer
    content_hash: common_schema.ContentHash
    provenance: common_schema.Provenance
    timing: Timing
