# @generated by tools/generate_contracts.py from contracts/schemas/ — DO NOT EDIT (repo-arch §13).

from __future__ import annotations

from enum import StrEnum
from typing import Any, TypeAlias

Manufacturability: TypeAlias = Any


class ManufacturabilityVerdictStatus(StrEnum):
    MANUFACTURABLE = "MANUFACTURABLE"
    NOT_MANUFACTURABLE = "NOT_MANUFACTURABLE"
    PLAN_INVALID = "PLAN_INVALID"
    INFRA_ERROR = "INFRA_ERROR"


class ManufacturabilityReasonCode(StrEnum):
    CAPABILITY_MISSING = "CAPABILITY_MISSING"
    PRECEDENCE_VIOLATION = "PRECEDENCE_VIOLATION"
    RESOURCE_UNAVAILABLE = "RESOURCE_UNAVAILABLE"
    TOLERANCE_UNSUPPORTED = "TOLERANCE_UNSUPPORTED"
    MATERIAL_UNSUPPORTED = "MATERIAL_UNSUPPORTED"
    PLAN_MALFORMED = "PLAN_MALFORMED"
