# @generated by tools/generate_contracts.py from contracts/schemas/ — DO NOT EDIT (repo-arch §13).

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any, Literal

from .. import common_schema


@dataclass
class Metadata:
    """
    Excluded from identity view.
    """

    author: str | None = None
    created_at: common_schema.Rfc3339 | None = None


class StockForm(StrEnum):
    """
    Closed enum (machined-part domain). Member change = MAJOR.
    """

    bar = "bar"
    plate = "plate"
    sheet = "sheet"
    block = "block"
    tube = "tube"


class ProcessOp(StrEnum):
    """
    Closed enum (machined-part domain). Member change = MAJOR.
    """

    cut_stock = "cut_stock"
    face_mill = "face_mill"
    drill = "drill"
    pocket_mill = "pocket_mill"
    turn = "turn"
    deburr = "deburr"
    inspect = "inspect"


@dataclass
class DeclaredOperation:
    op: ProcessOp
    target: str | None = None
    params: dict[str, Any] | None = None


@dataclass
class Tolerances:
    general_tolerance_mm: float


@dataclass
class StepArtifactRef:
    """
    OPAQUE reference to an attached STEP file. RM1 never parses geometry (spec §7).
    """

    media_type: Literal["model/step"]
    id: common_schema.Uuid
    content_hash: common_schema.ContentHash


@dataclass
class ManufacturingRequest:
    """
    The real engineer-facing input (RM1 spec §7; contract package §3.1). Demonstration domain: Machined Part. schema_version 1.0.0. Identity view excludes request_id and metadata.
    """

    schema_version: common_schema.SemVer
    request_id: common_schema.Uuid
    material: str
    stock_form: StockForm
    declared_operations: list[DeclaredOperation]
    quantity: int
    material_code: str | None = None
    tolerances: Tolerances | None = None
    step_artifact_ref: StepArtifactRef | None = None
    metadata: Metadata | None = None
