# @generated by tools/generate_contracts.py from contracts/schemas/ — DO NOT EDIT (repo-arch §13).

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from .. import common_schema
from . import design_input_schema, manufacturability_schema


class PrecedentSignal(StrEnum):
    """
    Closed enum (report-level derived signal). Member change = MAJOR.
    """

    SUPPORTING = "SUPPORTING"
    CAUTIONARY = "CAUTIONARY"
    NONE = "NONE"


@dataclass
class PrecedentEntry:
    """
    Precedent-entry data (contract package §3). No independent id/content_hash; grounded by episode_ref.content_hash.
    """

    rank: int
    episode_ref: common_schema.Ref
    relevance_score: int
    verdict_status: manufacturability_schema.ManufacturabilityVerdictStatus
    reason_codes: list[manufacturability_schema.ManufacturabilityReasonCode]
    precedent_verification_status: design_input_schema.EngineeringVerificationStatus


@dataclass
class PrecedentReport:
    """
    RM3 Engineering Precedent Reasoning output (contract package §4). Advisory only; the report carries NO query-verdict field (structural honesty). schema_version 1.0.0. Identity view excludes report_id, content_hash, and provenance; report_id = uuid5(NS_MP, content_hash). References frozen RM1 enums (ManufacturabilityVerdictStatus/ManufacturabilityReasonCode/EngineeringVerificationStatus); reuses common primitives unchanged.
    """

    schema_version: common_schema.SemVer
    report_id: common_schema.Uuid
    query_design_input_ref: common_schema.Ref
    precedents: list[PrecedentEntry]
    signal: PrecedentSignal
    signal_source_rank: int | None
    precedent_model_version: common_schema.SemVer
    content_hash: common_schema.ContentHash
    provenance: common_schema.Provenance
