# @generated by tools/generate_contracts.py from contracts/schemas/ — DO NOT EDIT (repo-arch §13).

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from .. import common_schema
from . import manufacturing_request_schema


@dataclass
class ProcessStep:
    index: int
    op: manufacturing_request_schema.ProcessOp
    required_capability: str
    inputs: list[str]
    provenance_ref: common_schema.Ref
    params: dict[str, Any] | None = None


@dataclass
class ResourceAssignment:
    step_index: int
    resource_id: str
    capability_id: str


@dataclass
class ProductionPlan:
    """
    The tangible manufacturing artifact: an ordered, resource-assigned process routing (package §3.4). schema_version 1.0.0. plan_id is deterministic = uuid5(NS_MP, content_hash). Identity view excludes plan_id, content_hash (self), and provenance timing.
    """

    schema_version: common_schema.SemVer
    plan_id: common_schema.Uuid
    task_ref: common_schema.Ref
    steps: list[ProcessStep]
    resource_assignments: list[ResourceAssignment]
    capability_model_version: common_schema.SemVer
    content_hash: common_schema.ContentHash
    provenance: common_schema.Provenance
