"""RM11 test helpers. Every job below is a declared TEST INPUT (operation times included), not
manufacturing data.

Canonical order is request_id ascending, so ID_A < ID_B < ID_C. The expected schedules used by the
tests are hand-computed in specs/milestones/RM11-multi-job-schedule.md §9 — never generated by the
implementation.
"""

from __future__ import annotations

import support
from mini_prometheus.intake.request_intake import intake
from mini_prometheus.manufacturing_constraints.capability_model import (
    ProcessCapabilityModel,
    default_model,
)
from mini_prometheus.manufacturing_constraints.oracle import ManufacturabilityOracle
from mini_prometheus.manufacturing_planning import planner
from mini_prometheus.manufacturing_scheduling.job_set import job_prerequisite_refusals
from mini_prometheus.manufacturing_scheduling.model import SchedulingJob
from mini_prometheus.orchestration.schedule_runner import schedule_requests
from support import FIXED_TIME

ID_A = "aaaaaaaa-0000-4000-8000-000000000001"
ID_B = "bbbbbbbb-0000-4000-8000-000000000002"
ID_C = "cccccccc-0000-4000-8000-000000000003"
TIMED_ID = "11111111-1111-1111-1111-111111111111"  # the RM10 fixture's request_id

THREE_JOB_FILES = ("rm11_jobs/job_a.json", "rm11_jobs/job_b.json", "rm11_jobs/job_c.json")

# Hand-computed earliest_start_v1 schedule of the three-job fixture (spec §9.1), canonical order:
# (request_id, step_index, op, resource_id, start_min, end_min)
THREE_JOB_SCHEDULE = [
    (ID_A, 0, "cut_stock", "saw01", 0, 10),
    (ID_A, 1, "face_mill", "mill01", 10, 40),
    (ID_B, 0, "cut_stock", "saw01", 10, 15),
    (ID_B, 1, "turn", "lathe01", 15, 35),
    (ID_C, 0, "cut_stock", "saw01", 15, 23),
    (ID_A, 2, "inspect", "cmm01", 40, 45),
    (ID_B, 2, "drill", "mill01", 40, 50),
    (ID_B, 3, "inspect", "cmm01", 50, 55),
    (ID_C, 1, "pocket_mill", "mill01", 50, 62),
    (ID_C, 2, "deburr", "bench01", 62, 68),
]
TIMED_TIMELINE = [(0, 12), (12, 47), (47, 65), (65, 83), (83, 93), (93, 108)]  # RM10 (ADR-0012)


def raw_job(
    request_id: str, operations: list[tuple[str, object]], *, material: str = "Aluminum 6061"
) -> dict:
    """A request whose operations carry the given duration_min (None = no duration declared)."""
    declared = []
    for op, duration in operations:
        entry: dict = {"op": op}
        if duration is not None:
            entry["params"] = {"duration_min": duration}
        declared.append(entry)
    return {
        "schema_version": "1.0.0",
        "request_id": request_id,
        "material": material,
        "stock_form": "block",
        "declared_operations": declared,
        "quantity": 1,
    }


def request(request_id: str, operations: list[tuple[str, object]], **kwargs):
    return support.build_request(raw_job(request_id, operations, **kwargs))


def three_job_raw() -> list[dict]:
    return [support.load_json(name) for name in THREE_JOB_FILES]


def three_job_requests():
    return [support.build_request(raw) for raw in three_job_raw()]


def timed_request():
    return support.build_request(support.load_json("engineer_request_with_durations.json"))


def shared_machine_requests(long_job_id: str = ID_B, short_job_id: str = ID_A):
    """Spec §9.2: a 10-min saw job and a saw 10 -> mill 100 job competing for saw01 at t=0."""
    return [
        request(short_job_id, [("cut_stock", 10)]),
        request(long_job_id, [("cut_stock", 10), ("face_mill", 100)]),
    ]


def independent_requests():
    """Spec §9.3: a mill-only job and a saw -> bench job (disjoint machines)."""
    return [request(ID_A, [("face_mill", 100)]), request(ID_B, [("cut_stock", 5), ("deburr", 5)])]


def schedule(requests, model: ProcessCapabilityModel | None = None, produced_at: str = FIXED_TIME):
    return schedule_requests(requests, capability_model=model, produced_at=produced_at)


def scheduling_jobs(requests, model: ProcessCapabilityModel | None = None) -> list[SchedulingJob]:
    """The schedulable jobs of a request list (every prerequisite asserted), in the given order."""
    model = model or default_model()
    jobs = []
    for req in requests:
        design_input = intake(req, produced_at=FIXED_TIME)
        task, plan = planner.plan(design_input, model, produced_at=FIXED_TIME)
        verdict = ManufacturabilityOracle().verify(plan, model)
        assert job_prerequisite_refusals(req.request_id, design_input, plan, verdict) == []
        jobs.append(SchedulingJob(req.request_id, task.task_id, plan))
    return jobs


def placements(sched) -> list[tuple]:
    return [
        (o.request_id, o.step_index, o.op, o.resource_id, o.start_min, o.end_min)
        for o in sched.operations
    ]


def twin_model() -> ProcessCapabilityModel:
    """default_model() plus a second mill (mill02) — the RM9 reroute test model."""
    base = default_model()
    return ProcessCapabilityModel(
        version=base.version,
        op_capability=base.op_capability,
        resources={**base.resources, "mill02": frozenset({"cap.mill", "cap.drill"})},
        supported_materials=base.supported_materials,
    )
