# @generated by tools/generate_contracts.py from contracts/schemas/ — DO NOT EDIT (repo-arch §13).

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, TypeAlias

Common: TypeAlias = Any


ContentHash: TypeAlias = str


Uuid: TypeAlias = str


SemVer: TypeAlias = str


Rfc3339: TypeAlias = str


@dataclass
class Ref:
    """
    Ref-by-hash: a reference is valid only if the referent's recomputed content_hash matches.
    """

    id: Uuid
    content_hash: ContentHash


@dataclass
class ProducedBy:
    component: str
    version: SemVer


@dataclass
class Provenance:
    """
    First-class derivation record (Law 18). produced_at is EXCLUDED from every content_hash.
    """

    source_refs: list[Ref]
    rule_id: str
    rule_version: SemVer
    capability_model_version: SemVer
    produced_by: ProducedBy
    produced_at: Rfc3339
