# @generated by tools/generate_contracts.py from contracts/schemas/ — DO NOT EDIT (repo-arch §13).

from __future__ import annotations

from typing import TypeAlias

from ... import common_schema

NoeticaProvenance: TypeAlias = common_schema.Provenance
