# @generated by tools/generate_contracts.py from contracts/schemas/ — DO NOT EDIT (repo-arch §13).

from __future__ import annotations

from dataclasses import dataclass

from ... import common_schema


@dataclass
class Verdict:
    """
    CONSUMED STUB — owned by Noetica (Law 15). RM1 pins this envelope until the real Noetica contract publishes. The envelope is domain-generic; MP fills status/reason_codes from its OWN closed taxonomies (manufacturing/manufacturability.schema.json). is_error carries Noetica's outcome/error distinction: RM1 maps INFRA_ERROR -> is_error:true (no episode), all others -> is_error:false. MP must not extend this envelope (Law 6).
    """

    grounded: bool
    is_error: bool
    status: str
    reason_codes: list[str]
    produced_by: common_schema.ProducedBy
    detail: str | None = None
