#!/usr/bin/env python3
"""Generate language bindings from the frozen JSON Schema contracts.

Source of truth: contracts/schemas/**.schema.json. Output: contracts/python/ (typed
dataclasses + enums; NO business logic). Bindings are GENERATED — never hand-edited
(repository-architecture.md §13). Re-run after any schema change; CI diffs the result.

Usage:  python3 tools/generate_contracts.py
Requires: datamodel-code-generator (see pyproject [dev]).
"""
from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SCHEMAS = REPO / "contracts" / "schemas"
OUT = REPO / "contracts" / "python"

HEADER = "# @generated by tools/generate_contracts.py from contracts/schemas/ — DO NOT EDIT (repo-arch §13)."


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    # Stage only *.schema.json (preserving structure) so codegen never sees .md/other files.
    with tempfile.TemporaryDirectory() as tmp:
        stage = Path(tmp) / "schemas"
        for src in SCHEMAS.rglob("*.schema.json"):
            dst = stage / src.relative_to(SCHEMAS)
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
        cmd = [
            sys.executable, "-m", "datamodel_code_generator",
            "--input", str(stage),
            "--input-file-type", "jsonschema",
            "--output", str(OUT),
            "--output-model-type", "dataclasses.dataclass",
            "--target-python-version", "3.11",
            "--use-schema-description",
            "--use-title-as-name",
            "--disable-timestamp",
            "--custom-file-header", HEADER,
            "--use-double-quotes",
        ]
        print("running:", " ".join(cmd))
        return subprocess.call(cmd)


if __name__ == "__main__":
    raise SystemExit(main())
