"""RM11 — multi-job deterministic scheduling (earliest_start_v1; NOT an optimizer).

Frozen rules: specs/milestones/RM11-multi-job-schedule.md. Test numbers follow the Director's RM11
list (17 is in test_rm11_checker.py, 20 in tests/integration/test_rm11_schedule_runner.py). Every
expected placement, makespan, lower bound and gap below is hand-computed in the spec (§9) — never
generated by the implementation.
"""

from __future__ import annotations

import dataclasses
import itertools
import os
import pathlib
import subprocess
import sys
import textwrap

import pytest

import rm11_support as s
from mini_prometheus import _hashing as h
from mini_prometheus._contracts import ProducedBy, Verdict
from mini_prometheus.intake.request_intake import intake
from mini_prometheus.manufacturing_constraints.capability_model import (
    default_model,
    with_unavailable_resources,
)
from mini_prometheus.manufacturing_planning import planner
from mini_prometheus.manufacturing_scheduling.earliest_start import earliest_start_v1
from mini_prometheus.manufacturing_scheduling.job_set import job_prerequisite_refusals
from mini_prometheus.manufacturing_scheduling.lower_bound import lower_bound
from mini_prometheus.manufacturing_scheduling.model import (
    MODEL_ASSUMPTIONS,
    BoundStatus,
    Refusal,
    RefusalReason,
    ScheduleStatus,
    schedule_digest,
    schedule_input_identity,
    schedule_view,
)
from rm11_support import ID_A, ID_B, ID_C, TIMED_ID
from support import FIXED_TIME

MILL_OPS = ("face_mill", "drill", "pocket_mill")


def _scheduled(requests, model=None):
    outcome = s.schedule(requests, model)
    assert outcome.status == ScheduleStatus.SCHEDULED and outcome.refusals == ()
    return outcome.schedule


def _refused(requests, model=None):
    outcome = s.schedule(requests, model)
    assert outcome.status == ScheduleStatus.NOT_SCHEDULED and outcome.schedule is None
    return outcome.refusals


# ---- 1-6: the rule, exactly ----
def test_01_one_job_schedule_equals_rm10_timeline():
    sched = _scheduled([s.timed_request()])
    (job,) = s.scheduling_jobs([s.timed_request()])
    rm10 = [
        (st.params["schedule_start_min"], st.params["schedule_end_min"]) for st in job.plan.steps
    ]
    assert [(o.start_min, o.end_min) for o in sched.operations] == rm10 == s.TIMED_TIMELINE
    assert [o.resource_id for o in sched.operations] == [
        a.resource_id for a in job.plan.resource_assignments
    ]
    assert sched.makespan_min == planner.lead_time_min(job.plan) == 108
    assert (
        sched.lower_bound_min,
        sched.lower_bound_binding_request_ids,
        sched.lower_bound_binding_resource_ids,
        sched.gap_to_lower_bound_min,
        sched.bound_status,
    ) == (108, (TIMED_ID,), (), 0, BoundStatus.PROVABLY_OPTIMAL)


def test_02_two_independent_jobs_on_different_machines_run_in_parallel():
    sched = _scheduled(s.independent_requests())
    assert s.placements(sched) == [
        (ID_A, 0, "face_mill", "mill01", 0, 100),
        (ID_B, 0, "cut_stock", "saw01", 0, 5),
        (ID_B, 1, "deburr", "bench01", 5, 10),
    ]
    assert {j.request_id: j.completion_min for j in sched.jobs} == {ID_A: 100, ID_B: 10}
    assert (
        sched.makespan_min,
        sched.lower_bound_min,
        sched.lower_bound_binding_request_ids,
        sched.lower_bound_binding_resource_ids,
        sched.gap_to_lower_bound_min,
        sched.bound_status,
    ) == (100, 100, (ID_A,), ("mill01",), 0, BoundStatus.PROVABLY_OPTIMAL)


def test_03_two_jobs_sharing_one_machine():
    sched = _scheduled(s.shared_machine_requests())
    assert s.placements(sched) == [
        (ID_A, 0, "cut_stock", "saw01", 0, 10),
        (ID_B, 0, "cut_stock", "saw01", 10, 20),
        (ID_B, 1, "face_mill", "mill01", 20, 120),
    ]
    assert (
        sched.makespan_min,
        sched.lower_bound_min,
        sched.lower_bound_binding_request_ids,
        sched.lower_bound_binding_resource_ids,
        sched.gap_to_lower_bound_min,
        sched.bound_status,
    ) == (120, 110, (ID_B,), (), 10, BoundStatus.GAP_ABOVE_LOWER_BOUND)


def test_04_job_precedence_preserved():
    sched = _scheduled(s.three_job_requests())
    assert s.placements(sched) == s.THREE_JOB_SCHEDULE
    for request_id in (ID_A, ID_B, ID_C):
        ops = sorted(
            (o for o in sched.operations if o.request_id == request_id), key=lambda o: o.step_index
        )
        assert [o.step_index for o in ops] == list(range(len(ops)))
        assert all(later.start_min >= earlier.end_min for earlier, later in itertools.pairwise(ops))


def test_05_machine_no_overlap_with_touching_intervals_allowed():
    sched = _scheduled(s.three_job_requests())
    for machine in sorted({o.resource_id for o in sched.operations}):
        intervals = sorted(
            (o.start_min, o.end_min) for o in sched.operations if o.resource_id == machine
        )
        assert all(nxt[0] >= prev[1] for prev, nxt in itertools.pairwise(intervals)), machine
    mill = sorted((o.start_min, o.end_min) for o in sched.operations if o.resource_id == "mill01")
    assert mill == [
        (10, 40),
        (40, 50),
        (50, 62),
    ]  # back-to-back: [a, b) then [b, c) is not an overlap


def test_06_exact_tie_is_decided_by_request_id_not_by_content_or_order():
    first = _scheduled(s.shared_machine_requests())  # the short saw job holds ID_A
    assert s.placements(first)[0] == (ID_A, 0, "cut_stock", "saw01", 0, 10)
    swapped = _scheduled(s.shared_machine_requests(long_job_id=ID_A, short_job_id=ID_B))
    assert s.placements(swapped) == [
        (ID_A, 0, "cut_stock", "saw01", 0, 10),
        (ID_A, 1, "face_mill", "mill01", 10, 110),
        (ID_B, 0, "cut_stock", "saw01", 10, 20),
    ]
    assert (
        swapped.makespan_min,
        swapped.lower_bound_min,
        swapped.gap_to_lower_bound_min,
        swapped.bound_status,
    ) == (110, 110, 0, BoundStatus.PROVABLY_OPTIMAL)


# ---- 7: determinism ----
def test_07_every_permutation_of_the_input_gives_a_byte_identical_schedule():
    reference = _scheduled(s.three_job_requests())
    canonical = h.canonical_json(schedule_view(reference))
    for permutation in itertools.permutations(s.three_job_requests()):
        sched = _scheduled(list(permutation))
        assert sched == reference
        assert h.canonical_json(schedule_view(sched)) == canonical


def test_07_generator_itself_ignores_argument_order():
    jobs = s.scheduling_jobs(s.three_job_requests())
    assert earliest_start_v1(list(reversed(jobs)), "1.0.0") == earliest_start_v1(jobs, "1.0.0")
    tie = s.scheduling_jobs(s.shared_machine_requests())
    assert earliest_start_v1(list(reversed(tie)), "1.0.0") == earliest_start_v1(tie, "1.0.0")


def test_07_hash_seed_does_not_change_the_schedule():
    reference = _scheduled(s.three_job_requests())
    root = pathlib.Path(__file__).resolve().parents[2]
    code = textwrap.dedent("""
        import enum
        if not hasattr(enum, "StrEnum"):
            class StrEnum(str, enum.Enum):
                pass
            enum.StrEnum = StrEnum
        import rm11_support as s
        sched = s.schedule(s.three_job_requests()).schedule
        print(sched.schedule_input_identity, sched.schedule_digest)
    """)
    path = os.pathsep.join(str(p) for p in (root, root / "src", root / "tests"))
    outputs = {
        subprocess.run(
            [sys.executable, "-c", code],
            env={**os.environ, "PYTHONPATH": path, "PYTHONHASHSEED": seed},
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
        for seed in ("0", "1", "4242")
    }
    assert outputs == {f"{reference.schedule_input_identity} {reference.schedule_digest}"}


def test_07_clock_does_not_change_the_schedule():
    a = _scheduled(s.three_job_requests())
    b = s.schedule(s.three_job_requests(), produced_at="2031-01-01T00:00:00+00:00").schedule
    assert a == b


# ---- 8-11: all-or-nothing refusals ----
def test_08_duplicate_request_id_rejected():
    refusals = _refused(
        [s.request(ID_A, [("cut_stock", 10)]), s.request(ID_A, [("face_mill", 20)])]
    )
    assert refusals == (
        Refusal(
            RefusalReason.DUPLICATE_REQUEST_ID,
            ID_A,
            "request_id appears 2 times; each job must be unique",
        ),
    )


def test_09_non_manufacturable_job_rejected_and_nothing_is_scheduled():
    requests = [
        *s.three_job_requests()[:2],
        s.request(ID_C, [("cut_stock", 8), ("deburr", 6)], material="Titanium Grade 5"),
    ]
    assert _refused(requests) == (
        Refusal(
            RefusalReason.JOB_NOT_MANUFACTURABLE, ID_C, "NOT_MANUFACTURABLE [MATERIAL_UNSUPPORTED]"
        ),
    )


@pytest.mark.parametrize(
    "operations,detail",
    [
        (
            [("cut_stock", None), ("deburr", None)],
            "no operation declares duration_min (RM10 timing not requested)",
        ),
        ([("cut_stock", 5), ("deburr", None)], "step 1 (deburr): duration_min missing"),
        (
            [("cut_stock", 5), ("deburr", 2.5)],
            "step 1 (deburr): duration_min invalid (2.5); must be an integer >= 1",
        ),
    ],
)
def test_10_job_missing_a_valid_rm10_timeline_rejected(operations, detail):
    refusals = _refused([s.request(ID_A, [("cut_stock", 10)]), s.request(ID_B, operations)])
    assert refusals == (Refusal(RefusalReason.JOB_TIMELINE_MISSING, ID_B, detail),)


def test_11_missing_machine_assignment_rejected_with_every_applicable_reason():
    model = with_unavailable_resources(default_model(), ["lathe01"])
    refusals = _refused(
        [s.request(ID_A, [("cut_stock", 10)]), s.request(ID_B, [("cut_stock", 5), ("turn", 20)])],
        model,
    )
    assert refusals == (
        Refusal(
            RefusalReason.JOB_NOT_MANUFACTURABLE,
            ID_B,
            "NOT_MANUFACTURABLE [RESOURCE_UNAVAILABLE] (RESOURCE_UNAVAILABLE: lathe01)",
        ),
        Refusal(RefusalReason.JOB_OPERATION_UNASSIGNED, ID_B, "no machine assigned: step 1 (turn)"),
        Refusal(RefusalReason.JOB_TIMELINE_MISSING, ID_B, "step 1 (turn): no machine assigned"),
    )


def test_11_unassigned_operation_is_refused_even_under_a_manufacturable_verdict():
    (job,) = s.scheduling_jobs([s.timed_request()])
    design_input = intake(s.timed_request(), produced_at=FIXED_TIME)
    plan = dataclasses.replace(
        job.plan,
        resource_assignments=[a for a in job.plan.resource_assignments if a.step_index != 4],
    )
    claimed = Verdict(
        grounded=True,
        is_error=False,
        status="MANUFACTURABLE",
        reason_codes=[],
        produced_by=ProducedBy(component="test", version="0.0.0"),
    )
    assert job_prerequisite_refusals(TIMED_ID, design_input, plan, claimed) == [
        Refusal(
            RefusalReason.JOB_OPERATION_UNASSIGNED, TIMED_ID, "no machine assigned: step 4 (deburr)"
        )
    ]


def test_every_refusal_is_reported_in_canonical_order_whatever_the_input_order():
    requests = [
        s.request(ID_C, [("cut_stock", None)]),
        s.request(ID_A, [("cut_stock", 10)], material="Unobtainium"),
        s.request(ID_B, [("cut_stock", 5)]),
        s.request(ID_B, [("cut_stock", 6)]),
    ]
    results = {_refused(list(p)) for p in itertools.permutations(requests)}
    assert len(results) == 1
    (refusals,) = results
    assert [(r.reason, r.request_id) for r in refusals] == [
        (RefusalReason.JOB_NOT_MANUFACTURABLE, ID_A),
        (RefusalReason.DUPLICATE_REQUEST_ID, ID_B),
        (RefusalReason.JOB_TIMELINE_MISSING, ID_C),
    ]


def test_empty_job_set_rejected():
    assert _refused([]) == (Refusal(RefusalReason.EMPTY_JOB_SET, None, "no job was given"),)


# ---- 12-16: completeness, makespan, lower bound, gap ----
def test_12_all_jobs_present_in_output():
    sched = _scheduled(s.three_job_requests())
    jobs = s.scheduling_jobs(s.three_job_requests())
    assert [(c.request_id, c.task_id, c.plan_content_hash) for c in sched.jobs] == [
        (j.request_id, j.task_id, j.plan.content_hash) for j in jobs
    ]
    assert [c.completion_min for c in sched.jobs] == [45, 55, 68]
    assert len(sched.operations) == sum(len(j.plan.steps) for j in jobs) == 10


def test_13_no_operation_duplicated_or_missing():
    sched = _scheduled(s.three_job_requests())
    keys = [(o.request_id, o.step_index) for o in sched.operations]
    jobs = s.scheduling_jobs(s.three_job_requests())
    assert len(keys) == len(set(keys))
    assert set(keys) == {(j.request_id, st.index) for j in jobs for st in j.plan.steps}


def test_14_makespan_is_the_latest_operation_end():
    sched = _scheduled(s.three_job_requests())
    assert sched.makespan_min == max(o.end_min for o in sched.operations) == 68
    independent = _scheduled(
        s.independent_requests()
    )  # the last-placed operation ends at 10, not 100
    assert independent.operations[-1].end_min == 10 and independent.makespan_min == 100


@pytest.mark.parametrize(
    "requests,expected",
    [
        (
            s.three_job_requests,
            (52, (), ("mill01",)),
        ),  # job totals 45/40/26; mill01 load 30+10+12 = 52
        (s.shared_machine_requests, (110, (ID_B,), ())),  # job B 10+100; saw01 20, mill01 100
        (s.independent_requests, (100, (ID_A,), ("mill01",))),
        (lambda: [s.timed_request()], (108, (TIMED_ID,), ())),
    ],
)
def test_15_lower_bound(requests, expected):
    sched = _scheduled(requests())
    bound = lower_bound(s.scheduling_jobs(requests()))
    assert (
        bound.lower_bound_min,
        bound.binding_request_ids,
        bound.binding_resource_ids,
    ) == expected
    assert (
        sched.lower_bound_min,
        sched.lower_bound_binding_request_ids,
        sched.lower_bound_binding_resource_ids,
    ) == expected
    total = sum(o.duration_min for o in sched.operations)
    assert sched.lower_bound_min <= sched.makespan_min <= total


@pytest.mark.parametrize(
    "requests,gap,status",
    [
        (s.three_job_requests, 16, BoundStatus.GAP_ABOVE_LOWER_BOUND),
        (s.shared_machine_requests, 10, BoundStatus.GAP_ABOVE_LOWER_BOUND),
        (s.independent_requests, 0, BoundStatus.PROVABLY_OPTIMAL),
        (lambda: [s.timed_request()], 0, BoundStatus.PROVABLY_OPTIMAL),
    ],
)
def test_16_gap_to_lower_bound(requests, gap, status):
    sched = _scheduled(requests())
    assert sched.gap_to_lower_bound_min == sched.makespan_min - sched.lower_bound_min == gap
    assert sched.bound_status == status


def test_16_bound_status_never_claims_suboptimality():
    assert [m.value for m in BoundStatus] == ["PROVABLY_OPTIMAL", "GAP_ABOVE_LOWER_BOUND"]


# ---- 18-19: fixed assignment and RM9 identity ----
def test_18_fixed_machine_assignment_retained():
    sched = _scheduled(s.three_job_requests())
    jobs = s.scheduling_jobs(s.three_job_requests())
    assigned = {
        (j.request_id, a.step_index): a.resource_id
        for j in jobs
        for a in j.plan.resource_assignments
    }
    assert all(o.resource_id == assigned[(o.request_id, o.step_index)] for o in sched.operations)
    twin = _scheduled(s.three_job_requests(), s.twin_model())  # a second mill exists and sits idle
    assert {o.resource_id for o in twin.operations if o.op in MILL_OPS} == {"mill01"}
    assert s.placements(twin) == s.THREE_JOB_SCHEDULE  # no reassignment during RM11


def test_19_rm9_irrelevant_availability_keeps_identity_relevant_changes_it():
    twin = s.twin_model()
    base = _scheduled(s.three_job_requests(), twin)
    irrelevant = _scheduled(s.three_job_requests(), with_unavailable_resources(twin, ["mill02"]))
    relevant = _scheduled(s.three_job_requests(), with_unavailable_resources(twin, ["mill01"]))
    assert irrelevant == base
    assert relevant.schedule_input_identity != base.schedule_input_identity
    assert relevant.schedule_digest != base.schedule_digest
    assert {o.resource_id for o in relevant.operations if o.op in MILL_OPS} == {
        "mill02"
    }  # RM9 reroute
    assert [(o.start_min, o.end_min) for o in relevant.operations] == [
        (o.start_min, o.end_min) for o in base.operations
    ]
    default_base = _scheduled(s.shared_machine_requests())
    assert _scheduled(
        s.shared_machine_requests(), with_unavailable_resources(default_model(), ["lathe01"])
    ) == (default_base)


def test_duration_change_changes_input_identity_and_digest():
    base = _scheduled(s.shared_machine_requests())
    changed = _scheduled(
        [
            s.request(ID_A, [("cut_stock", 11)]),
            s.request(ID_B, [("cut_stock", 10), ("face_mill", 100)]),
        ]
    )
    assert changed.schedule_input_identity != base.schedule_input_identity
    assert changed.schedule_digest != base.schedule_digest


# ---- metadata, identity vs digest, rule shape ----
def test_metadata_identifies_the_rule_and_does_not_claim_optimization():
    sched = _scheduled(s.three_job_requests())
    assert (
        sched.scheduling_rule,
        sched.scheduling_rule_version,
        sched.optimization_status,
        sched.capability_model_version,
    ) == ("earliest_start_v1", "1.0.0", "NOT_OPTIMIZED", "1.0.0")
    assert (
        sched.model_assumptions
        == MODEL_ASSUMPTIONS
        == (
            "one machine processes at most one operation at a time",
            "operations are non-preemptive",
            "each job is available at time 0",
            "each job preserves its RM10 step order",
            "each operation retains the machine assignment produced by RM9",
            "duration is the RM10 duration_min",
            "no setup/changeover time",
            "no transfer time",
            "no calendars/shifts/maintenance",
            "no due dates/release dates",
            "no flexible machine reassignment during RM11",
            "no optimization",
            "no execution/dispatch",
        )
    )


def test_input_identity_is_the_problem_not_the_answer():
    sched = _scheduled(s.three_job_requests())
    jobs = s.scheduling_jobs(s.three_job_requests())
    before_scheduling = schedule_input_identity(
        "earliest_start_v1",
        "1.0.0",
        "1.0.0",
        [(j.request_id, j.plan.content_hash) for j in reversed(jobs)],
    )
    assert sched.schedule_input_identity == before_scheduling
    other_answer = dataclasses.replace(sched, makespan_min=sched.makespan_min + 1)
    assert other_answer.schedule_input_identity == sched.schedule_input_identity
    assert schedule_digest(other_answer) != schedule_digest(sched) == sched.schedule_digest


def test_every_operation_is_left_justified():
    sched = _scheduled(s.three_job_requests())
    job_end: dict[str, int] = {}
    machine_end: dict[str, int] = {}
    for op in sched.operations:  # canonical order == placement order
        assert op.start_min == max(
            job_end.get(op.request_id, 0), machine_end.get(op.resource_id, 0)
        )
        job_end[op.request_id] = machine_end[op.resource_id] = op.end_min
