"""RM14 — sequence-dependent cross-job changeover (Director tests A-V).

Every expected schedule is hand-computed from the frozen rule (specs/milestones/
RM14-sequence-dependent-changeover.md §9) and never generated by the implementation. Default
capability model: saw01 cut_stock; mill01 face_mill/drill/pocket_mill; lathe01 turn; bench01
deburr; cmm01 inspect. Canonical order is request_id ascending: ID_A < ID_B < ID_C.
"""

from __future__ import annotations

import pytest

import rm11_support as s
import rm14_support as t
from mini_prometheus.intake.request_intake import intake
from mini_prometheus.manufacturing_constraints.capability_model import default_model
from mini_prometheus.manufacturing_scheduling.earliest_start import earliest_start_v1
from mini_prometheus.manufacturing_scheduling.job_set import schedule_job_set
from mini_prometheus.manufacturing_scheduling.model import (
    MODEL_ASSUMPTIONS,
    MODEL_ASSUMPTIONS_DOWNTIME_SETUP,
    MODEL_ASSUMPTIONS_SETUP,
    NO_SETUP_ASSUMPTION,
    BoundStatus,
    InvalidSetupError,
    JobInput,
    RefusalReason,
    ScheduleStatus,
    UnspecifiedSetupTransitionError,
    schedule_view,
)
from rm11_support import FIXED_TIME, ID_A, ID_B, ID_C
from rm14_support import R

TWO_MILL = {ID_A: [("face_mill", 10)], ID_B: [("pocket_mill", 20)]}
EXPLICIT = [R("mill01", "face_mill", "pocket_mill", 3), R("mill01", None, None, 9)]


def _scheduled(spec, rules, **kwargs):
    outcome = t.run(t.requests_of(spec), rules, **kwargs)
    assert outcome.status == ScheduleStatus.SCHEDULED, outcome.refusals
    return outcome.schedule


# --- A. validation (before planning; never a verdict or a refusal) --------------------------------
@pytest.mark.parametrize(
    "rules,message",
    [
        ([("mill01", None, None, -1)], "integer minutes >= 0"),
        ([("mill01", None, None, 2.5)], "integer minutes >= 0"),
        ([("mill01", None, None, "5")], "integer minutes >= 0"),
        ([("mill01", None, None, True)], "integer minutes >= 0"),
        ([("mill01", None, None)], "must be (machine_id, prev_op, curr_op, duration_min)"),
        (["mill01:drill:drill:5"], "must be (machine_id, prev_op, curr_op, duration_min)"),
        ([{"machine_id": "mill01"}], "must be (machine_id, prev_op, curr_op, duration_min)"),
        ([None], "must be (machine_id, prev_op, curr_op, duration_min)"),
        ([("mill01", "drill", None, 5)], "both be operation codes, or both None"),
        ([("mill01", None, "drill", 5)], "both be operation codes, or both None"),
        ([("mill99", None, None, 5)], "unknown machine id"),
        ([(None, None, None, 5)], "unknown machine id"),
        ([("mill01", "weld", "drill", 5)], "unknown operation"),
        ([("mill01", "ANY", "ANY", 5)], "unknown operation"),
        ([("mill01", "turn", "drill", 5)], "mill01 cannot perform turn"),
        ([("saw01", "drill", "drill", 5)], "saw01 cannot perform drill"),
        ([("mill01", None, None, 5), ("mill01", None, None, 5)], "declared twice"),
        (
            [R("mill01", "drill", "drill", 1), ("mill01", "drill", "drill", 2)],
            "declared twice",
        ),
        ("mill01:5", "collection"),
        ({"mill01": 5}, "collection"),
        ((rule for rule in [("mill01", None, None, 5)]), "collection"),
    ],
)
def test_A_invalid_setup_rules_are_rejected_before_planning(rules, message):
    with pytest.raises(InvalidSetupError) as exc:
        t.run(t.requests_of(TWO_MILL), rules)
    assert message in str(exc.value)


def test_A_validation_precedes_every_refusal():
    with pytest.raises(InvalidSetupError):
        schedule_job_set([], default_model(), setup_rules=[("mill01", None, None, -1)])


def test_A_rules_may_be_setup_rule_objects_or_four_item_sequences():
    as_objects = _scheduled(TWO_MILL, EXPLICIT)
    as_tuples = _scheduled(
        TWO_MILL, [("mill01", "face_mill", "pocket_mill", 3), ["mill01", None, None, 9]]
    )
    assert schedule_view(as_objects) == schedule_view(as_tuples)


# --- B/E. explicit transition rule, applied between two different jobs ----------------------------
def test_B_explicit_transition_beats_the_machine_default():
    sched = _scheduled(TWO_MILL, EXPLICIT)
    assert s.placements(sched) == [
        (ID_A, 0, "face_mill", "mill01", 0, 10),
        (ID_B, 0, "pocket_mill", "mill01", 13, 33),
    ]
    assert t.changeovers(sched) == [
        (ID_B, 0, "mill01", ID_A, "face_mill", "pocket_mill", "transition", 3, 10, 13)
    ]
    assert sched.scheduling_rule == "earliest_start_v1_setup"
    assert sched.setup_rules == (
        R("mill01", None, None, 9),
        R("mill01", "face_mill", "pocket_mill", 3),
    )
    assert (sched.makespan_min, sched.lower_bound_min, sched.gap_to_lower_bound_min) == (33, 30, 3)


# --- C. machine default: it beats absence ------------------------------------------------------
def test_C_machine_default_applies_without_a_transition_rule():
    rules = [R("mill01", "drill", "pocket_mill", 3), R("mill01", None, None, 9)]
    sched = _scheduled(TWO_MILL, rules)
    assert s.placements(sched)[1] == (ID_B, 0, "pocket_mill", "mill01", 19, 39)
    assert t.changeovers(sched) == [
        (ID_B, 0, "mill01", ID_A, "face_mill", "pocket_mill", "machine_default", 9, 10, 19)
    ]
    assert sched.setup_rules == (R("mill01", None, None, 9),)  # drill -> pocket_mill cannot occur


# --- D. refusal only for a transition the rule needs; never assumed zero ----------------------
UNSPECIFIED = RefusalReason.UNSPECIFIED_SETUP_TRANSITION


def _undeclared(machine, prev_op, curr_op):
    return (
        f"{machine}: cross-job changeover {prev_op} -> {curr_op} is not declared and {machine} has "
        "no declared default"
    )


def test_D_an_unused_theoretical_transition_does_not_cause_a_refusal():
    # pocket_mill -> face_mill is possible but never evaluated: at t=0 both operations are first on
    # mill01 (no changeover), A's goes first, then B's pocket_mill follows A's face_mill
    sched = _scheduled(TWO_MILL, [R("mill01", "face_mill", "pocket_mill", 3)])
    assert t.changeovers(sched) == [
        (ID_B, 0, "mill01", ID_A, "face_mill", "pocket_mill", "transition", 3, 10, 13)
    ]
    assert sched.setup_rules == (R("mill01", "face_mill", "pocket_mill", 3),)


def test_D_an_actually_required_undeclared_transition_refuses_the_set():
    outcome = t.run(t.requests_of(TWO_MILL), [R("mill01", "pocket_mill", "face_mill", 3)])
    assert outcome.status == ScheduleStatus.NOT_SCHEDULED and outcome.schedule is None
    assert [(r.reason, r.request_id, r.detail) for r in outcome.refusals] == [
        (UNSPECIFIED, None, _undeclared("mill01", "face_mill", "pocket_mill"))
    ]


def test_D_a_machine_whose_rules_cannot_apply_still_refuses_a_needed_transition():
    spec = {ID_A: [("drill", 10)], ID_B: [("drill", 5)]}  # face_mill never occurs on mill01
    outcome = t.run(t.requests_of(spec), [R("mill01", "face_mill", "drill", 3)])
    assert [(r.reason, r.detail) for r in outcome.refusals] == [
        (UNSPECIFIED, _undeclared("mill01", "drill", "drill"))  # needed: refused, not zero
    ]


def test_D_every_needed_undeclared_transition_of_the_decision_is_reported_in_any_order():
    spec = {ID_A: [("face_mill", 10)], ID_B: [("drill", 5)], ID_C: [("pocket_mill", 5)]}
    rules = [R("mill01", "drill", "pocket_mill", 1)]  # after A's face_mill, B and C both need one
    expected = [
        (UNSPECIFIED, _undeclared("mill01", "face_mill", "drill")),
        (UNSPECIFIED, _undeclared("mill01", "face_mill", "pocket_mill")),
    ]
    for requests in (t.requests_of(spec), list(reversed(t.requests_of(spec)))):
        outcome = t.run(requests, rules)
        assert [(r.reason, r.detail) for r in outcome.refusals] == expected


def test_D_changeover_refusal_arises_only_when_the_set_is_scheduled():
    spec = {**TWO_MILL, ID_C: [("cut_stock", None)]}  # C lacks a timeline: nothing is scheduled
    outcome = t.run(t.requests_of(spec), [R("mill01", "pocket_mill", "face_mill", 3)])
    assert [(r.reason, r.request_id) for r in outcome.refusals] == [
        (RefusalReason.JOB_TIMELINE_MISSING, ID_C)
    ]


def test_D_the_generator_never_invents_an_undeclared_changeover():
    jobs = s.scheduling_jobs(t.requests_of(TWO_MILL))
    with pytest.raises(UnspecifiedSetupTransitionError) as exc:
        earliest_start_v1(jobs, "1.0.0", setup_rules=(R("mill01", "face_mill", "drill", 3),))
    assert exc.value.transitions == (("mill01", "face_mill", "pocket_mill"),)


# --- F. no changeover inside one job --------------------------------------------------------------
def test_F_consecutive_operations_of_one_job_have_no_changeover():
    spec = {ID_A: [("face_mill", 10), ("drill", 5)], ID_B: [("pocket_mill", 20)]}
    sched = _scheduled(spec, [R("mill01", None, None, 7)])
    assert s.placements(sched) == [
        (ID_A, 0, "face_mill", "mill01", 0, 10),
        (ID_A, 1, "drill", "mill01", 10, 15),  # same job: no changeover
        (ID_B, 0, "pocket_mill", "mill01", 22, 42),
    ]
    assert t.changeovers(sched) == [
        (ID_B, 0, "mill01", ID_A, "drill", "pocket_mill", "machine_default", 7, 15, 22)
    ]


def test_F_a_machine_used_by_one_job_never_has_a_changeover():
    spec = {ID_A: [("face_mill", 10), ("drill", 5)], ID_B: [("cut_stock", 5)]}
    with_rules = _scheduled(
        spec, [R("mill01", None, None, 7), R("mill01", "face_mill", "drill", 4)]
    )
    assert schedule_view(with_rules) == schedule_view(_scheduled(spec, None))


# --- G/S/T. first operation, machine-specific rules, single-operation machine ---------------------
SAW_MILL = {ID_A: [("cut_stock", 10), ("face_mill", 10)], ID_B: [("cut_stock", 5), ("drill", 5)]}


def test_G_T_first_operation_on_each_machine_has_no_changeover_and_saw_default_applies():
    sched = _scheduled(SAW_MILL, [R("saw01", None, None, 2), R("mill01", None, None, 4)])
    assert s.placements(sched) == [
        (ID_A, 0, "cut_stock", "saw01", 0, 10),  # first on saw01: no changeover
        (ID_A, 1, "face_mill", "mill01", 10, 20),  # first on mill01 (not at t=0): none either
        (ID_B, 0, "cut_stock", "saw01", 12, 17),
        (ID_B, 1, "drill", "mill01", 24, 29),
    ]
    assert t.changeovers(sched) == [
        (ID_B, 0, "saw01", ID_A, "cut_stock", "cut_stock", "machine_default", 2, 10, 12),
        (ID_B, 1, "mill01", ID_A, "face_mill", "drill", "machine_default", 4, 20, 24),
    ]


def test_S_rules_are_machine_specific():
    rules = [
        R("saw01", None, None, 2),
        R("mill01", None, None, 4),
        R("mill01", "face_mill", "drill", 6),
    ]
    sched = _scheduled(SAW_MILL, rules)
    assert s.placements(sched)[3] == (ID_B, 1, "drill", "mill01", 26, 31)
    assert t.changeovers(sched)[1] == (
        ID_B,
        1,
        "mill01",
        ID_A,
        "face_mill",
        "drill",
        "transition",
        6,
        20,
        26,
    )
    assert t.changeovers(sched)[0][6:8] == ("machine_default", 2)  # saw01 keeps its own default


def test_T_single_operation_machine_with_an_explicit_same_operation_rule():
    rules = [R("saw01", "cut_stock", "cut_stock", 3), R("mill01", None, None, 4)]
    sched = _scheduled(SAW_MILL, rules)
    assert s.placements(sched)[2:] == [
        (ID_B, 0, "cut_stock", "saw01", 13, 18),
        (ID_B, 1, "drill", "mill01", 24, 29),
    ]
    assert t.changeovers(sched)[0] == (
        ID_B,
        0,
        "saw01",
        ID_A,
        "cut_stock",
        "cut_stock",
        "transition",
        3,
        10,
        13,
    )


# --- H/I. a changeover occupies the machine; it ends exactly where its operation starts -----------
def test_H_I_changeover_consumes_machine_capacity_and_is_adjacent():
    spec = {ID_A: [("cut_stock", 10)], ID_B: [("cut_stock", 10)], ID_C: [("cut_stock", 10)]}
    sched = _scheduled(spec, [R("saw01", None, None, 5)])
    assert s.placements(sched) == [
        (ID_A, 0, "cut_stock", "saw01", 0, 10),
        (ID_B, 0, "cut_stock", "saw01", 15, 25),
        (ID_C, 0, "cut_stock", "saw01", 30, 40),  # waits for B's changeover AND B's cut
    ]
    assert [c[8:] for c in t.changeovers(sched)] == [(10, 15), (25, 30)]
    starts = {(o.request_id, o.step_index): o.start_min for o in sched.operations}
    assert all(c.end_min == starts[(c.request_id, c.step_index)] for c in sched.setups)
    assert (sched.makespan_min, sched.lower_bound_min, sched.bound_status) == (
        40,
        30,
        BoundStatus.GAP_ABOVE_LOWER_BOUND,
    )


# --- J. no anticipatory setup ---------------------------------------------------------------------
def test_J_changeover_never_starts_before_the_jobs_predecessor_completes():
    spec = {ID_A: [("face_mill", 10)], ID_B: [("cut_stock", 30), ("pocket_mill", 10)]}
    sched = _scheduled(spec, [R("mill01", None, None, 8)])
    # mill01 is idle from 10, but B's part is on saw01 until 30: the changeover starts at 30, not 22
    assert s.placements(sched)[-1] == (ID_B, 1, "pocket_mill", "mill01", 38, 48)
    assert t.changeovers(sched) == [
        (ID_B, 1, "mill01", ID_A, "face_mill", "pocket_mill", "machine_default", 8, 30, 38)
    ]


# --- K/L/V. RM12 downtime: changeover + operation is one block outside downtime -------------------
SAW_TWO = {ID_A: [("cut_stock", 10)], ID_B: [("cut_stock", 10)]}


@pytest.mark.parametrize(
    "minutes,downtime,expected_setup,expected_cut",
    [
        # K: the changeover alone would fit before [16, 20), the block does not
        (5, [(16, 20)], (20, 25), (25, 35)),
        # L: pushed past three windows to the first gap that holds the whole block
        (5, [(12, 20), (30, 33), (40, 60)], (60, 65), (65, 75)),
        # V: a long changeover whose block ends exactly at the downtime start (half-open) fits
        (30, [(50, 55)], (10, 40), (40, 50)),
        # V: one minute more and the whole block moves after the downtime
        (30, [(49, 55)], (55, 85), (85, 95)),
    ],
)
def test_K_L_V_block_never_intersects_downtime(minutes, downtime, expected_setup, expected_cut):
    sched = _scheduled(SAW_TWO, [R("saw01", None, None, minutes)], downtime={"saw01": downtime})
    assert s.placements(sched) == [
        (ID_A, 0, "cut_stock", "saw01", 0, 10),
        (ID_B, 0, "cut_stock", "saw01", *expected_cut),
    ]
    assert [c[8:] for c in t.changeovers(sched)] == [expected_setup]
    assert sched.scheduling_rule == "earliest_start_v1_downtime_setup"
    assert sched.model_assumptions == MODEL_ASSUMPTIONS_DOWNTIME_SETUP


def test_K_lower_bounds_are_unchanged_by_changeover():
    sched = _scheduled(SAW_TWO, [R("saw01", None, None, 5)], downtime={"saw01": [(16, 20)]})
    plain = _scheduled(SAW_TWO, None, downtime={"saw01": [(16, 20)]})
    assert (sched.lower_bound_min, sched.window_aware_lower_bound_min) == (20, 24)
    assert (plain.lower_bound_min, plain.window_aware_lower_bound_min) == (20, 24)
    assert sched.gap_to_lower_bound_min == 35 - 24


# --- M/N/O. identity: relevant rules only, canonical ----------------------------------------------
def _identity(spec, rules):
    return _scheduled(spec, rules).schedule_input_identity


def test_M_a_relevant_rule_change_changes_the_identity():
    base = _identity(TWO_MILL, EXPLICIT)
    assert _identity(TWO_MILL, [R("mill01", "face_mill", "pocket_mill", 4), EXPLICIT[1]]) != base
    assert _identity(TWO_MILL, [EXPLICIT[0], R("mill01", None, None, 8)]) != base
    assert _identity(TWO_MILL, None) != base


def test_N_irrelevant_rules_change_neither_identity_nor_digest():
    base = _scheduled(TWO_MILL, EXPLICIT)
    extra = [
        R("saw01", None, None, 5),  # saw01 unused
        R("mill01", "drill", "face_mill", 2),  # drill never occurs
        R("lathe01", "turn", "turn", 1),  # lathe01 unused
    ]
    noisy = _scheduled(TWO_MILL, EXPLICIT + extra)
    assert (noisy.schedule_input_identity, noisy.schedule_digest) == (
        base.schedule_input_identity,
        base.schedule_digest,
    )


def test_N_a_default_covering_no_possible_transition_is_irrelevant():
    complete = [
        R("mill01", "face_mill", "pocket_mill", 3),
        R("mill01", "pocket_mill", "face_mill", 6),
    ]
    with_default = _scheduled(TWO_MILL, [*complete, R("mill01", None, None, 9)])
    assert with_default.setup_rules == tuple(complete)
    assert schedule_view(with_default) == schedule_view(_scheduled(TWO_MILL, complete))


def test_O_equivalent_inputs_have_one_canonical_identity():
    base = _scheduled(TWO_MILL, EXPLICIT)
    for rules in (
        list(reversed(EXPLICIT)),
        tuple(EXPLICIT),
        {("mill01", "face_mill", "pocket_mill", 3), ("mill01", None, None, 9)},
        [["mill01", None, None, 9], ("mill01", "face_mill", "pocket_mill", 3)],
    ):
        other = _scheduled(TWO_MILL, rules)
        assert (other.schedule_input_identity, other.schedule_digest) == (
            base.schedule_input_identity,
            base.schedule_digest,
        )


# --- P. no RM14 relevance: exactly the earlier behaviour (full golden gate in the zero-diff file) -
@pytest.mark.parametrize("rules", [None, [], ()])
def test_P_absent_or_empty_rules_are_exactly_rm13(rules):
    sched = _scheduled(TWO_MILL, rules)
    assert sched.scheduling_rule == "earliest_start_v1" and sched.setups == ()
    assert sched.model_assumptions == MODEL_ASSUMPTIONS and NO_SETUP_ASSUMPTION in MODEL_ASSUMPTIONS
    assert "setup_rules" not in schedule_view(sched) and "setups" not in schedule_view(sched)


def test_P_one_job_reproduces_rm10_whatever_rules_are_declared():
    rules = [R(m, None, None, 50) for m in ("saw01", "mill01", "lathe01", "bench01", "cmm01")]
    with_rules = t.run([s.timed_request()], rules)
    assert schedule_view(with_rules.schedule) == schedule_view(t.run([s.timed_request()]).schedule)


# --- R. determinism ------------------------------------------------------------------------------
def test_R_same_input_same_output_in_any_job_order():
    rules = [R("saw01", None, None, 2), R("mill01", None, None, 4)]
    first = t.run(t.requests_of(SAW_MILL), rules)
    again = t.run(t.requests_of(SAW_MILL), list(reversed(rules)))
    reversed_jobs = t.run(list(reversed(t.requests_of(SAW_MILL))), rules)
    assert schedule_view(first.schedule) == schedule_view(again.schedule)
    assert schedule_view(first.schedule) == schedule_view(reversed_jobs.schedule)


# --- U. zero-minute changeover --------------------------------------------------------------------
def test_U_zero_minute_changeover_is_recorded_and_changes_nothing_else():
    sched = _scheduled(SAW_TWO, [R("saw01", None, None, 0)])
    plain = _scheduled(SAW_TWO, None)
    assert s.placements(sched) == s.placements(plain)
    assert t.changeovers(sched) == [
        (ID_B, 0, "saw01", ID_A, "cut_stock", "cut_stock", "machine_default", 0, 10, 10)
    ]
    assert sched.scheduling_rule == "earliest_start_v1_setup"
    assert sched.model_assumptions == MODEL_ASSUMPTIONS_SETUP
    assert NO_SETUP_ASSUMPTION not in sched.model_assumptions
    assert sched.schedule_input_identity != plain.schedule_input_identity  # declared, so identified


# --- RM9 / RM13 boundaries ------------------------------------------------------------------------
def test_changeover_never_reroutes_to_another_machine():
    twin = s.twin_model()  # mill02 could take every mill operation; RM9's assignment stays fixed
    costly = t.run(s.three_job_requests(), [R("mill01", None, None, 100)], capability_model=twin)
    plain = t.run(s.three_job_requests(), capability_model=twin)

    def machines(outcome):
        return {(o.request_id, o.step_index): o.resource_id for o in outcome.schedule.operations}

    assert machines(costly) == machines(plain)
    assert costly.schedule.setups and costly.schedule.makespan_min > plain.schedule.makespan_min


def test_rm13_remaining_work_excludes_changeover():
    spec = {
        ID_A: [("face_mill", 10), ("deburr", 30)],
        ID_B: [("drill", 5), ("deburr", 15)],  # remaining processing 20, changeover 0
        ID_C: [("pocket_mill", 15)],  # remaining processing 15, changeover 10
    }
    rules = [R("mill01", None, None, 10), R("mill01", "face_mill", "drill", 0)]
    sched = _scheduled(spec, rules, rule=t.MWKR)
    assert sched.scheduling_rule == "earliest_start_v1_most_work_remaining_setup"
    # at t=10 B (20 processing) goes before C (15 processing + 10 changeover = 25 if it counted)
    mill = [o for o in sched.operations if o.resource_id == "mill01"]
    assert [(o.request_id, o.start_min, o.end_min) for o in mill] == [
        (ID_A, 0, 10),
        (ID_B, 10, 15),
        (ID_C, 25, 40),
    ]
    assert sched.makespan_min == 55


def test_the_generator_records_only_the_relevant_declared_rules():
    jobs = s.scheduling_jobs(t.requests_of(TWO_MILL))
    declared = (  # canonical, as the job set passes them; two rules cannot apply
        R("mill01", None, None, 9),
        R("mill01", "drill", "face_mill", 2),
        EXPLICIT[0],
        R("saw01", None, None, 5),
    )
    direct = earliest_start_v1(jobs, "1.0.0", setup_rules=declared)
    assert direct.setup_rules == (R("mill01", None, None, 9), EXPLICIT[0])
    inputs = [
        JobInput(r.request_id, intake(r, produced_at=FIXED_TIME)) for r in t.requests_of(TWO_MILL)
    ]
    via_job_set = schedule_job_set(
        inputs, default_model(), produced_at=FIXED_TIME, setup_rules=EXPLICIT
    ).schedule
    assert schedule_view(direct) == schedule_view(via_job_set)
