"""RM12 — time-aware resource downtime scheduling (earliest_start_v1_downtime; NOT an optimizer).

Frozen rules: specs/milestones/RM12-resource-downtime.md. Letters follow the Director's RM12 test
list (A and K are in test_rm12_no_downtime_zero_diff.py, V in test_rm12_checker.py, AC in
tests/integration/test_rm12_cli.py, AD in tools/verify_installed_wheel.py). Every expected
placement, bound and gap is hand-computed in the spec (§8) — never generated by the implementation.
"""

from __future__ import annotations

import itertools

import pytest

import rm11_support as s
from mini_prometheus.manufacturing_constraints.capability_model import (
    default_model,
    with_unavailable_resources,
)
from mini_prometheus.manufacturing_scheduling.downtime import canonical_downtime, relevant_downtime
from mini_prometheus.manufacturing_scheduling.lower_bound import (
    available_by,
    lower_bound,
    window_aware_lower_bound,
)
from mini_prometheus.manufacturing_scheduling.model import (
    MODEL_ASSUMPTIONS,
    MODEL_ASSUMPTIONS_DOWNTIME,
    BoundStatus,
    InvalidDowntimeError,
    ScheduleStatus,
    schedule_input_identity,
)
from mini_prometheus.manufacturing_scheduling.model import DowntimeInterval as D
from mini_prometheus.orchestration.runner import run_from_request
from mini_prometheus.orchestration.schedule_runner import schedule_requests
from rm11_support import FIXED_TIME, ID_A, ID_B, ID_C

KNOWN = default_model().resources
LETTER = {ID_A: "A", ID_B: "B", ID_C: "C"}
MILL_OPS = ("face_mill", "drill", "pocket_mill")
# Spec §8.1: the three-job fixture with mill01 down on [20, 45)
THREE_JOB_MILL_DOWN = [
    ("A", 0, "cut_stock", "saw01", 0, 10),
    ("B", 0, "cut_stock", "saw01", 10, 15),
    ("B", 1, "turn", "lathe01", 15, 35),
    ("C", 0, "cut_stock", "saw01", 15, 23),
    ("A", 1, "face_mill", "mill01", 45, 75),
    ("A", 2, "inspect", "cmm01", 75, 80),
    ("B", 2, "drill", "mill01", 75, 85),
    ("B", 3, "inspect", "cmm01", 85, 90),
    ("C", 1, "pocket_mill", "mill01", 85, 97),
    ("C", 2, "deburr", "bench01", 97, 103),
]


def _run(requests, downtime, model=None, produced_at=FIXED_TIME):
    outcome = schedule_requests(
        requests, capability_model=model, produced_at=produced_at, downtime=downtime
    )
    assert outcome.status == ScheduleStatus.SCHEDULED and outcome.refusals == ()
    return outcome.schedule


def _placements(sched):
    return [
        (LETTER[o.request_id], o.step_index, o.op, o.resource_id, o.start_min, o.end_min)
        for o in sched.operations
    ]


def _single(duration, downtime, op="face_mill"):
    sched = _run([s.request(ID_A, [(op, duration)])], downtime)
    ((_letter, _step, _op, _machine, start, end),) = _placements(sched)
    return start, end


# ---- canonicalization and validation (D, E, M-R) ----
def test_D_overlapping_intervals_are_merged():
    assert canonical_downtime({"mill01": [(50, 100), (75, 130)]}, KNOWN) == {
        "mill01": (D(50, 130),)
    }


def test_E_touching_intervals_are_merged():
    assert canonical_downtime({"mill01": [(60, 120), (120, 180)]}, KNOWN) == {
        "mill01": (D(60, 180),)
    }


def test_canonical_form_is_sorted_disjoint_non_touching_and_order_independent():
    spans = [(300, 310), (10, 50), (20, 30), (10, 50), (49, 60), D(59, 61)]
    expected = {"mill01": (D(10, 61), D(300, 310)), "saw01": (D(0, 1),)}
    for order in itertools.permutations(spans[:4]):
        given = {"saw01": [(0, 1)], "mill01": [*order, *spans[4:]], "lathe01": []}
        result = canonical_downtime(given, KNOWN)
        assert result == expected and list(result) == ["mill01", "saw01"]  # empty machine omitted
    assert canonical_downtime(None, KNOWN) == {} == canonical_downtime({}, KNOWN)


def test_M_unknown_machine_is_rejected_never_ignored():
    with pytest.raises(InvalidDowntimeError, match="unknown machine id\\(s\\) in downtime: mill99"):
        canonical_downtime({"mill99": [(0, 10)], "mill01": [(0, 10)]}, KNOWN)
    with pytest.raises(InvalidDowntimeError, match="mill99"):  # before any planning or refusal
        schedule_requests([s.request(ID_A, [("cut_stock", None)])], downtime={"mill99": [(0, 1)]})


@pytest.mark.parametrize(
    "case,interval,message",
    [
        ("N_end_before_start", (10, 5), "must end after it starts"),
        ("O_zero_length", (5, 5), "must end after it starts"),
        ("P_negative", (-5, 10), "starts before 0"),
        ("Q_fractional", (2.5, 10), "must be finite integer minutes"),
        ("Q_integral_float", (0, 10.0), "must be finite integer minutes"),
        ("Q_boolean", (True, 5), "must be finite integer minutes"),
        ("Q_text", ("0", "10"), "must be finite integer minutes"),
        ("R_unbounded_infinity", (0, float("inf")), "must be finite integer minutes"),
        ("R_unbounded_none", (0, None), "must be finite integer minutes"),
        ("malformed_triple", (1, 2, 3), "must be a \\(start_min, end_min\\) pair"),
        ("malformed_scalar", 5, "must be a \\(start_min, end_min\\) pair"),
    ],
)
def test_N_to_R_invalid_intervals_are_rejected(case, interval, message):
    with pytest.raises(InvalidDowntimeError, match=message):
        canonical_downtime({"mill01": [interval]}, KNOWN)


# ---- placement (B, C, F, G, H, I, J) ----
def test_B_one_downtime_interval():
    sched = _run(s.three_job_requests(), {"mill01": [(20, 45)]})
    assert _placements(sched) == THREE_JOB_MILL_DOWN
    assert [c.completion_min for c in sched.jobs] == [80, 90, 103]


def test_C_multiple_non_overlapping_intervals_leave_the_gap_between_usable():
    assert _single(10, {"mill01": [(5, 10), (25, 30)]}) == (10, 20)


def test_F_operation_ending_exactly_at_downtime_start_is_not_shifted():
    assert _single(20, {"mill01": [(20, 30)]}) == (0, 20)


def test_G_operation_starting_exactly_at_downtime_end():
    sched = _run([s.request(ID_A, [("cut_stock", 10), ("face_mill", 20)])], {"mill01": [(0, 10)]})
    assert [(o.start_min, o.end_min) for o in sched.operations] == [(0, 10), (10, 30)]
    assert _single(20, {"mill01": [(0, 10)]}) == (10, 30)


def test_H_operation_that_would_cross_downtime_is_shifted_to_its_end():
    assert _single(20, {"mill01": [(10, 30)]}) == (30, 50)


def test_I_multiple_windows_shift_repeatedly():
    assert _single(20, {"mill01": [(5, 10), (25, 30)]}) == (30, 50)


def test_J_multiple_affected_machines():
    sched = _run(s.independent_requests(), {"mill01": [(0, 10)], "saw01": [(0, 3)]})
    assert _placements(sched) == [
        ("B", 0, "cut_stock", "saw01", 3, 8),
        ("B", 1, "deburr", "bench01", 8, 13),
        ("A", 0, "face_mill", "mill01", 10, 110),
    ]
    assert (sched.makespan_min, sched.lower_bound_min, sched.window_aware_lower_bound_min) == (
        110,
        100,
        110,
    )
    assert sched.gap_to_lower_bound_min == 0 and sched.bound_status == BoundStatus.PROVABLY_OPTIMAL


# ---- identity (L) and routing (S, T) ----
def test_L_relevant_downtime_changes_identity_rule_and_schedule():
    base = s.schedule(s.shared_machine_requests()).schedule
    down = _run(s.shared_machine_requests(), {"saw01": [(0, 5)]})
    assert _placements(down) == [
        ("A", 0, "cut_stock", "saw01", 5, 15),
        ("B", 0, "cut_stock", "saw01", 15, 25),
        ("B", 1, "face_mill", "mill01", 25, 125),
    ]
    assert (down.scheduling_rule, base.scheduling_rule) == (
        "earliest_start_v1_downtime",
        "earliest_start_v1",
    )
    assert down.schedule_input_identity != base.schedule_input_identity
    assert down.schedule_digest != base.schedule_digest
    later = _run(s.shared_machine_requests(), {"mill01": [(1000, 1010)]})  # used machine, no effect
    assert [(o.start_min, o.end_min) for o in later.operations] == [
        (o.start_min, o.end_min) for o in base.operations
    ]
    assert later.schedule_input_identity != base.schedule_input_identity  # relevance = machine used


def test_relevant_downtime_excludes_unused_machines_from_record_and_identity():
    twin = s.twin_model()
    only_mill01 = _run(s.three_job_requests(), {"mill01": [(20, 45)]}, twin)
    with_mill02 = _run(s.three_job_requests(), {"mill01": [(20, 45)], "mill02": [(0, 500)]}, twin)
    assert only_mill01 == with_mill02
    assert only_mill01.downtime == (("mill01", (D(20, 45),)),)


def test_S_downtime_never_reroutes_to_an_idle_capable_machine():
    sched = _run(s.three_job_requests(), {"mill01": [(0, 1000)]}, s.twin_model())
    mill = [o for o in sched.operations if o.op in MILL_OPS]
    assert {o.resource_id for o in mill} == {"mill01"} and min(o.start_min for o in mill) >= 1000


def test_T_machine_assignment_and_plans_are_unchanged(tmp_path):
    sched = _run(s.three_job_requests(), {"mill01": [(20, 45)]})
    jobs = s.scheduling_jobs(s.three_job_requests())
    assigned = {
        (j.request_id, a.step_index): a.resource_id
        for j in jobs
        for a in j.plan.resource_assignments
    }
    assert all(o.resource_id == assigned[(o.request_id, o.step_index)] for o in sched.operations)
    store = str(tmp_path / "e.jsonl")
    standalone = {
        r.request_id: run_from_request(r, produced_at=FIXED_TIME, store_path=store)
        for r in s.three_job_requests()
    }
    assert {c.request_id: c.plan_content_hash for c in sched.jobs} == {
        rid: result.plan.content_hash for rid, result in standalone.items()
    }


# ---- append-only (U) ----
def _fit(start, duration, intervals):
    shifted = True
    while shifted:  # an independent formulation: retry until no interval intersects
        shifted = False
        for a, b in intervals:
            if start < b and a < start + duration:
                start, shifted = b, True
    return start


def test_U_append_only_every_start_is_the_earliest_fit_after_job_and_machine():
    downtime = {"mill01": [(20, 45)], "saw01": [(12, 14)]}
    sched = _run(s.three_job_requests(), downtime)
    job_end: dict[str, int] = {}
    machine_end: dict[str, int] = {}
    starts = []
    for op in sched.operations:  # canonical order == placement order
        earliest = max(job_end.get(op.request_id, 0), machine_end.get(op.resource_id, 0))
        assert op.start_min == _fit(earliest, op.duration_min, downtime.get(op.resource_id, []))
        job_end[op.request_id] = machine_end[op.resource_id] = op.end_min
        starts.append(op.start_min)
    assert starts == sorted(starts)


# ---- bounds, makespan, gap (W, X, Y, Z) ----
def test_W_rm11_lower_bound_is_retained():
    sched = _run(s.three_job_requests(), {"mill01": [(20, 45)]})
    rm11 = lower_bound(s.scheduling_jobs(s.three_job_requests()))
    assert (sched.lower_bound_min, sched.lower_bound_binding_resource_ids) == (52, ("mill01",))
    assert (rm11.lower_bound_min, rm11.binding_resource_ids) == (52, ("mill01",))


@pytest.mark.parametrize(
    "work,intervals,expected",
    [
        (52, [(20, 45)], 77),  # 20 before the downtime, 32 after it
        (20, [(0, 5)], 25),
        (10, [(20, 45)], 10),  # fits before the downtime
        (20, [(20, 45)], 20),  # exactly the capacity before it
        (30, [(5, 10), (20, 40)], 55),  # 5 + 10 before, 15 after
        (0, [(0, 5)], 0),
    ],
)
def test_X_window_aware_machine_bound(work, intervals, expected):
    assert available_by(work, tuple(D(a, b) for a, b in intervals)) == expected


def test_X_window_aware_lower_bound_of_the_schedule():
    sched = _run(s.three_job_requests(), {"mill01": [(20, 45)]})
    assert (
        sched.window_aware_lower_bound_min,
        sched.window_aware_lower_bound_binding_resource_ids,
    ) == (77, ("mill01",))
    jobs = s.scheduling_jobs(s.three_job_requests())
    bound = window_aware_lower_bound(jobs, (("mill01", (D(20, 45),)),))
    assert (bound.lower_bound_min, bound.binding_resource_ids) == (77, ("mill01",))


def test_Y_makespan_is_the_latest_end():
    sched = _run(s.three_job_requests(), {"mill01": [(20, 45)]})
    assert sched.makespan_min == max(o.end_min for o in sched.operations) == 103


@pytest.mark.parametrize(
    "requests,downtime,makespan,lb11,lb12,gap,status",
    [
        (
            s.three_job_requests,
            {"mill01": [(20, 45)]},
            103,
            52,
            77,
            26,
            BoundStatus.GAP_ABOVE_LOWER_BOUND,
        ),
        (
            s.shared_machine_requests,
            {"saw01": [(0, 5)]},
            125,
            110,
            110,
            15,
            BoundStatus.GAP_ABOVE_LOWER_BOUND,
        ),
        (
            s.independent_requests,
            {"mill01": [(0, 10)], "saw01": [(0, 3)]},
            110,
            100,
            110,
            0,
            BoundStatus.PROVABLY_OPTIMAL,
        ),
    ],
)
def test_Z_gap_is_measured_to_the_window_aware_bound(
    requests, downtime, makespan, lb11, lb12, gap, status
):
    sched = _run(requests(), downtime)
    assert (sched.makespan_min, sched.lower_bound_min, sched.window_aware_lower_bound_min) == (
        makespan,
        lb11,
        lb12,
    )
    assert sched.gap_to_lower_bound_min == makespan - lb12 == gap and sched.bound_status == status
    assert lb11 <= lb12 <= makespan


# ---- determinism (AA, AB), metadata and identity ----
def test_AA_repeated_execution_and_clock_are_deterministic():
    first = _run(s.three_job_requests(), {"mill01": [(20, 45)]})
    again = _run(
        s.three_job_requests(), {"mill01": [(20, 45)]}, produced_at="2031-01-01T00:00:00+00:00"
    )
    assert first == again and first.schedule_digest == again.schedule_digest


def test_AB_input_order_permutations_give_a_byte_identical_schedule():
    reference = _run(s.three_job_requests(), {"mill01": [(20, 45)], "saw01": [(12, 14)]})
    for requests in itertools.permutations(s.three_job_requests()):
        downtime = {"saw01": [(12, 14)], "mill01": [(30, 45), (20, 30)]}  # reordered and split
        assert _run(list(requests), downtime) == reference


def test_metadata_records_the_downtime_rule_assumptions_and_canonical_downtime():
    sched = _run(s.three_job_requests(), {"mill01": [(30, 45), (20, 30)]})
    assert (sched.scheduling_rule, sched.scheduling_rule_version, sched.optimization_status) == (
        "earliest_start_v1_downtime",
        "1.0.0",
        "NOT_OPTIMIZED",
    )
    assert sched.model_assumptions == MODEL_ASSUMPTIONS_DOWNTIME
    assert MODEL_ASSUMPTIONS_DOWNTIME[: len(MODEL_ASSUMPTIONS)] == MODEL_ASSUMPTIONS
    assert sched.downtime == (("mill01", (D(20, 45),)),)


def test_input_identity_is_the_problem_including_relevant_downtime_not_the_answer():
    sched = _run(s.three_job_requests(), {"mill01": [(20, 45)]})
    jobs = s.scheduling_jobs(s.three_job_requests())
    relevant = relevant_downtime(canonical_downtime({"mill01": [(20, 45)]}, KNOWN), jobs)
    before = schedule_input_identity(
        "earliest_start_v1_downtime",
        "1.0.0",
        "1.0.0",
        [(j.request_id, j.plan.content_hash) for j in jobs],
        relevant,
    )
    assert sched.schedule_input_identity == before


def test_rm9_availability_and_rm12_downtime_compose_without_rerouting_by_downtime():
    model = with_unavailable_resources(s.twin_model(), ["mill01"])  # RM9 reroutes at planning
    sched = _run(s.three_job_requests(), {"mill02": [(20, 45)]}, model)
    assert {o.resource_id for o in sched.operations if o.op in MILL_OPS} == {"mill02"}
    assert [(o.start_min, o.end_min) for o in sched.operations if o.resource_id == "mill02"] == [
        (45, 75),
        (75, 85),
        (85, 97),
    ]
